language: android
jdk: oraclejdk8

install:
  - echo yes | sdkmanager "tools" &>/dev/null
  - echo yes | sdkmanager "platform-tools" &>/dev/null
  - echo yes | sdkmanager "build-tools;27.0.3" &>/dev/null
  - echo yes | sdkmanager "platforms;android-28" &>/dev/null

script:
  - ./gradlew clean testDebug lintDebug --stacktrace

#sudo: false

before_install:
  - chmod +x gradlew  # to prevent "Permission Denied" error

# Remove old local cache files before and cache again after the build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache