name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Perform base checks
        run: ./gradlew app:assembleDebug library:dokka --stacktrace
  ANDROID_UNIT_TESTS:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute unit tests
        run: ./gradlew library:testDebugUnitTest --stacktrace
  ANDROID_BUILD_APK:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute APK build
        run: ./gradlew app:assembleDebug --stacktrace
      # TODO: send notification message with artifact

      - uses: actions/upload-artifact@v2
        with:
          name: apk-files
          path: app/build/outputs/apk/**/*.apk